# Generated by Django 2.1.7 on 2019-03-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0002_auto_20190325_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='es_Nada',
            field=models.BooleanField(default=False),
        ),
    ]
