# Generated by Django 2.1.7 on 2019-04-06 19:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('homePage', '0004_auto_20190325_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoLiterario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GeneroLiterario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='infoLibro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Titulo', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=2000)),
                ('ISBN', models.IntegerField()),
                ('CantidadPaginas', models.IntegerField()),
                ('Idioma', models.CharField(max_length=15)),
                ('formato', models.ManyToManyField(to='homePage.FormatoLiterario')),
                ('genero', models.ManyToManyField(to='homePage.GeneroLiterario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='infousuario',
            name='aficiones',
            field=models.ManyToManyField(blank=True, to='homePage.Aficion'),
        ),
    ]
