# Generated by Django 2.1.7 on 2019-04-06 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0005_auto_20190406_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolibro',
            name='imagen',
            field=models.ImageField(default='images/books/covers/default.jpg', upload_to='images/books/covers/'),
        ),
    ]
