# Generated by Django 2.1.7 on 2019-04-06 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0006_infolibro_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infolibro',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
