# Generated by Django 2.2 on 2019-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0010_infolibro_preciolibro'),
    ]

    operations = [
        migrations.AddField(
            model_name='infousuario',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
