# Generated by Django 2.2 on 2019-04-14 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homePage', '0011_infousuario_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='cuentaPorCobrar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articuloLibro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='homePage.infoLibro')),
                ('usuarioComprador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentaporcobrar_usuarioComprador', to='homePage.infousuario')),
                ('usuarioPropioDelCobro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentaporcobrar_usuarioPropioDelCobro', to='homePage.infousuario')),
            ],
        ),
    ]
